apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-broker
  namespace: citrinos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amqp-broker
  template:
    metadata:
      labels:
        app: amqp-broker
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        livenessProbe:
          exec:
            command: [ "rabbitmq-diagnostics", "-q", "ping" ]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-broker
  namespace: citrinos
spec:
  selector:
    app: amqp-broker
  ports:
  - name: management
    port: 15672
    targetPort: 15672
  - name: amqp
    port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: citrinos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

