apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.citrine.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.citrine.name }}
  ports:
  {{- range .Values.citrine.ports }}
  - name: port-{{ .port }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}