{{- if .Values.grafanaIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana-ingress
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.grafanaIngress.clusterIssuer }}"
spec:
  ingressClassName: {{ .Values.grafanaIngress.className }}
  tls:
    - hosts:
        - {{ .Values.grafanaIngress.host }}
      secretName: {{ .Values.grafanaIngress.secretName }}
  rules:
    - host: {{ .Values.grafanaIngress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-grafana
                port:
                  number: {{ .Values.grafanaIngress.service.port }}
{{- end }}
