apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.rabbitmq.name }}
  ports:
  {{- range .Values.rabbitmq.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}