{{- if .Values.rabbitmq.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rabbitmq.name }}-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.rabbitmq.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }}